version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./app:/go/src/github.com/camiloperezv/dojo_go/app
    depends_on:
      - mongodb
    networks:
     - go_network2
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongoData:/data/db
      - mongoConfig:/data/configdb
    command: mongod
    networks:
     - go_network2
volumes:
  notused:
  mongoData:
  mongoConfig:
networks:
  go_network2:
    driver: bridge
